# Multi level Perceptron (MLP): Using Numpy and Pandas

* Develop and train a MLP model to accurately classify MNIST data. 
* Use one hidden layer, one input layer and one output layer. 
* Test and choose an appropriate activation function, Optimizer and loss function. 
* Implement forward-propagation and Back-propagation.

In [19]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt

## Loading MNIST data
Load data and mention data properties

In [20]:
# Loading test and train data
train_data_input = pd.read_csv('MNIST_CSV/mnist_train.csv', header=None)
test_data_input = pd.read_csv('MNIST_CSV/mnist_test.csv', header=None)

In [21]:
# Data properties

print('Data shape : ', train_data_input.shape)

print('Image length : ', train_data_input.iloc[1,1:].shape)

print('Feature Data type : ', type(train_data_input.iloc[1,1]))

print('Label Data type : ', type(train_data_input.iloc[0,0]))


Data shape :  (60000, 785)
Image length :  (784,)
Feature Data type :  <class 'numpy.int64'>
Label Data type :  <class 'numpy.int64'>


## Building the FC1 layer

Building the first fully connected layer of MPL. Using Weight and bias matrices to expand 


In [22]:
# Separating label and Normalizing data from 0 to 1

train_data = (train_data_input.iloc[:,1:] / 255).to_numpy()

y_train = train_data_input.iloc[:,0]

test_data = (test_data_input.iloc[:,1:]  / 255).to_numpy()

y_test = test_data_input.iloc[:,0]

print(f'Minimum and Maximum feature values: {train_data.min()}, {train_data.max()}')



Minimum and Maximum feature values: 0.0, 1.0


In [23]:
# Initializing weight and bias matrices with random values to break neuron symmetry
input_bias = ( np.random.random_sample((1, 256)) -0.05 ) * .01
input_weights = ( np.random.random_sample((784, 256)) -0.5 ) *.01


# Input layer function
def Layer_1(input_array = None):

    output_matrix = np.matmul(input_array , input_weights) + input_bias

    return output_matrix

FC1_output = Layer_1(train_data)


# Adding activation layer

Introducing non linearity in neurons through hidden layer to make model functionally strong. Using ReLU, Sigmoid and Tanh as activation functions. Compressing the layer to 512 neurons.

In [24]:
# Creating a function for activation layer

def Layer_activation(input_matrix = None, activation = 'ReLU'):

    if activation == 'ReLU':

        output_matrix = np.maximum(0, input_matrix)
    
        return output_matrix

Activation_output =  Layer_activation(FC1_output)


# Building FC2 layer

Building a second hidden fully connected layer to ensure gradual compression of neurons

In [25]:
# Layer_2 is a fully connected perceptron layer consisting of 256 neurons

# Initializing weight and bias matrices with random values to break neuron symmetry
FC2_weights = ( np.random.rand(1024,128) ) *.01

FC2_Bias = ( np.random.rand(1,128) ) *.01

def layer_2 (input_matrix = None):
    
    output_matrix = np.matmul( input_matrix , FC2_weights) + FC2_Bias

    return output_matrix

FC2_output = layer_2(Activation_output)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1024 is different from 256)

# Adding activation layer

Introducing another non linearity in neurons through hidden layer to make model functionally strong. Using ReLU, Sigmoid and Tanh as activation functions. 

Z3 = ReLU( ReLU( XW1 ) W2 ) W3

In [ ]:
# Creating a function for activation layer

def Layer_activation(input_matrix = None, activation = 'ReLU'):

    if activation == 'ReLU':

        output_matrix = np.maximum(0, input_matrix)
    
        return output_matrix

Activation_output =  Layer_activation(FC2_output)

# Output Layer

Output layer compress the FC2 output further into 10 classes (digits)

In [ ]:
# Initializing weight and bias matrices with random values to break neuron symmetry

output_weights = ( np.random.rand(256,10) ) *.01

output_bias = ( np.random.rand(1,10) ) *.01

def output_layer (input_matrix = None):

    output_matrix = np.matmul( input_matrix , output_weights ) + output_bias

    # print(output_matrix)

    sigmoid = 1 / ( 1 + np.exp(-output_matrix) )

    # print(output_matrix)

    return sigmoid

predictions = output_layer (Activation_output)

print(predictions.max(),predictions.min(),predictions)

0.5446608714025294 0.5129996892073917 [[0.52460239 0.52598435 0.5233521  ... 0.52663246 0.52380949 0.52500225]
 [0.52690694 0.52834161 0.52548855 ... 0.52906777 0.5260379  0.52726623]
 [0.52101019 0.52232966 0.51990267 ... 0.52279787 0.52027337 0.52144699]
 ...
 [0.5229465  0.52427894 0.52173327 ... 0.52485783 0.52217175 0.52333814]
 [0.52241846 0.52377591 0.52124472 ... 0.52431221 0.52163702 0.52284542]
 [0.52107148 0.52236656 0.51994754 ... 0.52286461 0.52032261 0.5214671 ]]
